In [1]:
# Text Representation - Bag Of Words (BOW)

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("spam.csv")
df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [4]:
df.Category.value_counts() # this shows how many spam and ham (regular emails) emails we have

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
# Create a new column 'spam' where spam = 1 and ham = 0
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [6]:
df.shape

(5572, 3)

In [7]:
df.head()

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [8]:
# Train test split

In [9]:
from sklearn.model_selection import train_test_split
# our X is the Message column and y is the spam column(1 for spam, 0 for ham)
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [10]:
X_train.shape # shape of 80% of messages.

(4457,)

In [11]:
X_test.shape

(1115,)

In [12]:
type(X_train) # pandas Series

pandas.core.series.Series

In [ ]:
X_train[:4] # first 4 messages in the training set
# 4227 is first message index in training set (these are random samples, thats why they are not in order)

4227    Ok thats cool. Its , just off either raglan rd...
2352    Download as many ringtones as u like no restri...
1999    Well, I have to leave for my class babe ... Yo...
4660    I cant pick the phone right now. Pls send a me...
Name: Message, dtype: object

In [14]:
type(y_train)

pandas.core.series.Series

In [ ]:
y_train[:4] # first 4 labels in the training set
# 1 means spam, 0 means ham

4227    0
2352    1
1999    0
4660    0
Name: spam, dtype: int64

In [16]:
type(X_train.values)

numpy.ndarray

In [17]:
# Create bag of words representation using CountVectorizer

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values) # when we use fit_transform, it learns the vocabulary and creates the bag of words model
X_train_cv # this is a sparse matrix representation of the bag of words model

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59107 stored elements and shape (4457, 7740)>

In [ ]:
X_train_cv.toarray()[:2][0] # first message array representation

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
X_train_cv.shape # (4457, 7740) -> 4457 messages and 7740 unique words in the vocabulary

(4457, 7740)

In [ ]:
v.get_feature_names_out()[1771] # checking which word is at index 1771 in the vocabulary

'cheating'

In [ ]:
v.vocabulary_ # this shows the mapping of words to their index in the vocabulary in the bag of words model

{'ok': 4909,
 'thats': 6812,
 'cool': 2025,
 'its': 3767,
 'just': 3874,
 'off': 4888,
 'either': 2560,
 'raglan': 5540,
 'rd': 5577,
 'or': 4961,
 'edward': 2543,
 'behind': 1331,
 'the': 6813,
 'cricket': 2097,
 'ground': 3260,
 'gimme': 3144,
 'ring': 5779,
 'when': 7475,
 'ur': 7199,
 'closeby': 1868,
 'see': 5980,
 'you': 7703,
 'tuesday': 7071,
 'download': 2437,
 'as': 1102,
 'many': 4350,
 'ringtones': 5784,
 'like': 4108,
 'no': 4789,
 'restrictions': 5743,
 '1000s': 264,
 'choose': 1822,
 'can': 1652,
 'even': 2667,
 'send': 6005,
 'yr': 7717,
 'buddys': 1567,
 'txt': 7093,
 'sir': 6181,
 'to': 6931,
 '80082': 644,
 'well': 7450,
 'have': 3364,
 'leave': 4056,
 'for': 2950,
 'my': 4666,
 'class': 1851,
 'babe': 1213,
 'never': 4751,
 'came': 1649,
 'back': 1220,
 'me': 4406,
 'hope': 3490,
 'nice': 4765,
 'sleep': 6215,
 'love': 4227,
 'cant': 1664,
 'pick': 5195,
 'phone': 5181,
 'right': 5773,
 'now': 4838,
 'pls': 5246,
 'message': 4458,
 'asked': 1114,
 'money': 4570,
 'h

In [ ]:
X_train_np = X_train_cv.toarray() # converting sparse matrix to a numpy array
X_train_np[0] # first message array representation

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
np.where(X_train_np[0]!=0) # in the first message, the indices where the word count is not zero.

(array([1331, 1868, 2025, 2097, 2543, 2560, 3144, 3260, 3767, 3874, 4888,
        4909, 4961, 5540, 5577, 5779, 5980, 6812, 6813, 7071, 7199, 7475,
        7703], dtype=int64),)

In [ ]:
X_train[:4] # first 4 messages in the training set

4227    Ok thats cool. Its , just off either raglan rd...
2352    Download as many ringtones as u like no restri...
1999    Well, I have to leave for my class babe ... Yo...
4660    I cant pick the phone right now. Pls send a me...
Name: Message, dtype: object

In [ ]:
X_train[:4][4227] # first message in the training set

'Ok thats cool. Its , just off either raglan rd or edward rd. Behind the cricket ground. Gimme ring when ur closeby see you tuesday.'

In [ ]:
X_train_np[0][1771] # checking the count of the word at index 1771 in the first message

0

In [31]:
# Train the naive bayes model

In [ ]:
# training the above bag of words model (X_train_cv) with Multinomial Naive Bayes again.
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv, y_train)

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [33]:
# we have bag of words model (X_train_cv) for training data, now we need to create bag of 
# words model for test data (X_test_cv).
X_test_cv = v.transform(X_test) # we only use transform here because we don't want to learn a new vocabulary, we want to use the existing one.

In [34]:
# Evaluate Performance

In [35]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv) # passing the test bag of words model (X_test_cv) to the trained model to get predictions

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       970
           1       0.99      0.94      0.96       145

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [ ]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails) # creating bag of words model for the new emails using the existing vocabulary
model.predict(emails_count) # passing the new emails bag of words model to the trained model (we again trained it using NB algorithm above) to get predictions

array([0, 1], dtype=int64)

In [37]:
# Train the model using sklearn pipeline and reduce number of lines of code

In [ ]:
from sklearn.pipeline import Pipeline
# here we are creating a pipeline with two steps: first step is CountVectorizer to create bag of words model, 
# second step is MultinomialNB to train the model
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])
# in return we got a clf object with bag of words model again trained on NB algorithm.

In [40]:
X_train

4227    Ok thats cool. Its , just off either raglan rd...
2352    Download as many ringtones as u like no restri...
1999    Well, I have to leave for my class babe ... Yo...
4660    I cant pick the phone right now. Pls send a me...
283                         Ok. I asked for money how far
                              ...                        
1222                               Prakesh is there know.
3922    Do 1 thing! Change that sentence into: "Becaus...
3560    URGENT! We are trying to contact U Todays draw...
2145    FreeMsg: Hey - I'm Buffy. 25 and love to satis...
3076    Take us out shopping and Mark will distract Is...
Name: Message, Length: 4457, dtype: object

In [41]:
y_train

4227    0
2352    1
1999    0
4660    0
283     0
       ..
1222    0
3922    0
3560    1
2145    1
3076    0
Name: spam, Length: 4457, dtype: int64

In [ ]:
clf.fit(X_train, y_train) # training the pipeline model with training data

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [ ]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       976
           1       0.98      0.93      0.95       139

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

